/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codingRound.mastertest;

import java.util.NoSuchElementException;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class Library {
	public static WebDriver driver;
	public static WebDriverWait wait;
	public Library(WebDriver driver)
	{
		Library.driver=driver;
		wait= new WebDriverWait(driver, 20);
	}
	
	
    public boolean someLibraryMethod() {
        return true;
    }
    
    public void click(WebDriver driver, WebElement element)
    {
    	wait.until(ExpectedConditions.visibilityOf(element));
    	element.click();
    }
    
    public void sendKeys(WebDriver driver, WebElement element,String value)
    {
    	wait.until(ExpectedConditions.visibilityOf(element));
    	element.sendKeys(value);
    }
    
    protected void waitFor(int durationInMilliSeconds) {
        try {
            Thread.sleep(durationInMilliSeconds);
        } catch (InterruptedException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        }
    }
    
    protected boolean isElementPresent(By by) {
        try {
            driver.findElement(by);
            return true;
        } catch (NoSuchElementException e) {
            return false;
        }
    }
    
    public void clearText(WebDriver driver, WebElement element)
    {
    	wait.until(ExpectedConditions.visibilityOf(element));
    	element.clear();
    }
    
}
